<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks />
      <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Unity.Wcf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Activation" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Web" />
  </ItemGroup>

</Project>
